repos:

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=99]
        exclude: /(\\.eggs|\\.git|\\.hg|\\.mypy_cache|\\.nox|\\.tox|\\.venv|_build|buck-out|build|dist|migrations|_pb2|pycoin)/

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        language_version: python3.10
        exclude: /(migrations|_pb2)/
        additional_dependencies: ["importlib-metadata==4.13.0"]
        args: [--max-line-length=99]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
        exclude: /(migrations|_pb2|pycoin|deprecated)/
        files: .*.py$
    -   id: trailing-whitespace
        exclude: /(migrations|_pb2|pycoin|deprecated)/
        files: .*.py$
    -   id: file-contents-sorter
        files: ^(requirements.*.txt)$

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
    -   id: bandit
        language_version: python3
        exclude: /(migrations|_pb2|pycoin|deprecated)/
        args: [ -r,  -c ,".bandit_scan.cfg", -f , "txt",  -o , "bandit_scan.log",  --baseline, ".bandit_baseline.json" , $(git ls-files) ]
        additional_dependencies: ["importlib-metadata==4.13.0"]

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1  # Use the latest version
    hooks:
      - id: autoflake
        args: [
          --in-place,
          --remove-all-unused-imports,
          --remove-unused-variables,
          --expand-star-imports,
          --ignore-init-module-imports,
        ]
